# Generated by Django 5.1 on 2024-08-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aNo', models.IntegerField()),
                ('aMsg', models.CharField(max_length=60)),
            ],
        ),
    ]
